[0m23:04:48.500099 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AEFE057820>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AE813CAC50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AE813CAA40>]}


============================== 23:04:48.506096 | 3800abe4-4679-4d59-b38e-380f8d72ede8 ==============================
[0m23:04:48.506096 [info ] [MainThread]: Running with dbt=1.7.0
[0m23:04:48.507097 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\joshi\\.dbt', 'debug': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run --debug', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m23:04:48.508630 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\joshi\OneDrive\Desktop\hit2\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m23:04:48.510590 [debug] [MainThread]: Command `dbt run` failed at 23:04:48.510590 after 0.07 seconds
[0m23:04:48.511590 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AEFE057820>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AE813CAA40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AE813CACE0>]}
[0m23:04:48.512722 [debug] [MainThread]: Flushing usage events
[0m23:09:02.299024 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027B1D9E6C80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027B20BBAB90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027B20BBA980>]}


============================== 23:09:02.304024 | 47b04d76-cf97-4f06-bf10-8b714389d546 ==============================
[0m23:09:02.304024 [info ] [MainThread]: Running with dbt=1.7.0
[0m23:09:02.305020 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\joshi\\.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run-operation test_source --args {"source_name": "raw", "table_name": "abr_data"}', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m23:09:02.306172 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\joshi\OneDrive\Desktop\hit2\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m23:09:02.308173 [debug] [MainThread]: Command `dbt run-operation` failed at 23:09:02.308173 after 0.07 seconds
[0m23:09:02.309171 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027B1D9E6C80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027B20BBA980>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027B20BBAC20>]}
[0m23:09:02.309171 [debug] [MainThread]: Flushing usage events
[0m23:13:45.997628 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000277950B6C80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002779828AB90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002779828A980>]}


============================== 23:13:46.001628 | 6581eaf2-2138-476b-b93b-1d70a7cb6a10 ==============================
[0m23:13:46.001628 [info ] [MainThread]: Running with dbt=1.7.0
[0m23:13:46.003629 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\joshi\\.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run-operation test_source --args {"source_name": "raw", "table_name": "abr_data"}', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m23:13:46.004627 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\joshi\OneDrive\Desktop\hit2\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m23:13:46.006544 [debug] [MainThread]: Command `dbt run-operation` failed at 23:13:46.005987 after 0.10 seconds
[0m23:13:46.007057 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000277950B6C80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002779828A980>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002779828AC20>]}
[0m23:13:46.008235 [debug] [MainThread]: Flushing usage events
